language: php

php:
  - 7.2
  - 7.3

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)